### ISSUE TITLE
SUGGESTION: MINI-MOD-Update for 'Much More Spiders V2'

### ISSUE THREAD

**Issue by markygnlg** [canitzp/SolarHelmet#4]
I'm guessing it's not a 'simple' mini-mod.. but from what I saw of your multi-pic-multi-gen-multi-optioned 'JustABattery' ... I have no choice but to ask...

Can yuo spent some time to see if you can replace [this](https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2) for ANY & ALL current versions (& every version in the world?!?!?!?!?)

[This ](https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2)mod creeped me out to the point that the hairs on different parts on my body would squirm depending on which/what spider I saw -- - - AT A DISTANCE!! FFs! I've seen monster-mods/creepy-mods, etc but [this ](https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2)is one of the 2 or 3 mods that REALLY made my  skin crawl!! & in minecraft!!

If you can then GREAT, but if not, then so be it -  BUT DUDE!! [IT'S](https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2) SOOOO CREEPY!! TEST [IT](https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2) !! PLS!!

..but if not, DO IT ANYWAYS!! DUDE!! [IT'S](https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2) SOOOO CREEPY!!

https://www.curseforge.com/minecraft/mc-mods/much-more-spiders-v2

**Comment by canitzp** [comment]
I won't update this mod. I can't just go and do that and alos entities/mods aren't the things I relly know a lot about

**Comment by markygnlg** [comment]
Some memories are better left as memories... thanks mate. Best wishes.
