### ISSUE TITLE
Solarhelmet has failed to load correctly

### ISSUE THREAD

**Issue by Baggytrousers27** [canitzp/SolarHelmet#6]
Forge 1.18 38.0.14
Solar helmet 1.2.2

SolarHelmet (solarhelmet) has failed to load correctly
java.lang.NoSuchMethodError: 'net.minecraftforge.fmllegacy.RegistryObject.

[Crashlog](https://pastebin.com/5XjdCzwm)

**Comment by canitzp** [comment]
You are using the wrong version of solar helmet. You are using the 1.17.1 version, but you need the 1.18 version.
The current 1.18 version is "Solar Helmet 38.0.0"

**Comment by Baggytrousers27** [comment]
Whoops ...
![1295910](https://user-images.githubusercontent.com/15883796/144772713-25ea9d74-f502-49a5-a006-470f11afaee5.jpg)
