### ISSUE TITLE
I can not charge at night - "producing energy while nighttime'

### ISSUE THREAD

**Issue by markygnlg** [canitzp/SolarHelmet#9]
I've tried:
energy_production_night_multiplier = 0.01 & 0.1 & 0.5

I've also tried:
#Base energy production of the helmet.
	energy_base_value = 150 (with the 3 'multiplier' settings above)

...and I tried:
energy_production_multiplier = 1.0 to a larger number but it defaulted back to "1.0" after restarting minecraft.

**Comment by canitzp** [comment]
Thank you for the report, I'll investigate it asap.

Would you please provide more information about your environment (Modloader, Versions, other mods)?

**Comment by markygnlg** [comment]
Too many mods to mention so I'll backup the savegame & remove all the mods - BRB...

 (Forge 47.2.0 / mc 1.20.1 / JustABattery-47.1.0.jar / SolarHelmet-47.0.1.jar .. I had another issue whereby the helmet would not charge when I placed it on my head 'manually', but when I put the 'solar helmet' in the toolbar & 'right-clicked', it then started working/charging)

It might be the mod: 'inventorio-1.20-forge-1.9.2.jar' &/or 'curios-forge-5.4.2+1.20.1.jar' combo?

...BRB

**Comment by canitzp** [comment]
I can confirm this issue. I actually haven't reintroduced the nighttime and rain multipliers, after changing the energy calculation.
It might take some time to add these to the current calculation.

**Comment by markygnlg** [comment]
Thanks. I'll close this issue since I have set the other settings to make it OP (&& justabattery too)... so it doesn't matter to me.
